version: 2.1

jobs:

  meh:
    docker:
      - image: dboneslabs/tools-docker-utils:latest
    steps:
      - checkout
      - run:
          name: version
          command: |
          
            echo done
                  
workflows:
  version: 2
  build_and_publish:
    jobs:
      - meh:
          filters:
            branches:
              ignore:
                - docs
